//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1209 with alias "adsListType"
	/// <summary>Ads List Type</summary>
	public partial interface IAdsListType : IPublishedContent
	{
		/// <summary>Ads List</summary>
		IEnumerable<IPublishedContent> AdsList { get; }
	}

	/// <summary>Ads List Type</summary>
	[PublishedContentModel("adsListType")]
	public partial class AdsListType : PublishedContentModel, IAdsListType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "adsListType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AdsListType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AdsListType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ads List
		///</summary>
		[ImplementPropertyType("adsList")]
		public IEnumerable<IPublishedContent> AdsList
		{
			get { return GetAdsList(this); }
		}

		/// <summary>Static getter for Ads List</summary>
		public static IEnumerable<IPublishedContent> GetAdsList(IAdsListType that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("adsList"); }
	}
}
