//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1215 with alias "adType"
	/// <summary>Ad Type</summary>
	public partial interface IAdType : IPublishedContent
	{
		/// <summary>Ad Code</summary>
		string AdCode { get; }

		/// <summary>Ad Image</summary>
		IPublishedContent AdImage { get; }

		/// <summary>Ad Link Url</summary>
		string AdLinkUrl { get; }
	}

	/// <summary>Ad Type</summary>
	[PublishedContentModel("adType")]
	public partial class AdType : PublishedContentModel, IAdType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "adType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AdType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AdType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ad Code
		///</summary>
		[ImplementPropertyType("adCode")]
		public string AdCode
		{
			get { return GetAdCode(this); }
		}

		/// <summary>Static getter for Ad Code</summary>
		public static string GetAdCode(IAdType that) { return that.GetPropertyValue<string>("adCode"); }

		///<summary>
		/// Ad Image
		///</summary>
		[ImplementPropertyType("adImage")]
		public IPublishedContent AdImage
		{
			get { return GetAdImage(this); }
		}

		/// <summary>Static getter for Ad Image</summary>
		public static IPublishedContent GetAdImage(IAdType that) { return that.GetPropertyValue<IPublishedContent>("adImage"); }

		///<summary>
		/// Ad Link Url
		///</summary>
		[ImplementPropertyType("adLinkUrl")]
		public string AdLinkUrl
		{
			get { return GetAdLinkUrl(this); }
		}

		/// <summary>Static getter for Ad Link Url</summary>
		public static string GetAdLinkUrl(IAdType that) { return that.GetPropertyValue<string>("adLinkUrl"); }
	}
}
