//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Article Ad Section</summary>
	[PublishedContentModel("articleAdSection")]
	public partial class ArticleAdSection : ContentSection, IAdType, IImageType, ISubtitleType, ITextType, ITitleType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "articleAdSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArticleAdSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArticleAdSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link 1
		///</summary>
		[ImplementPropertyType("link1")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker Link1
		{
			get { return this.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("link1"); }
		}

		///<summary>
		/// Link 2
		///</summary>
		[ImplementPropertyType("link2")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker Link2
		{
			get { return this.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("link2"); }
		}

		///<summary>
		/// Link 3
		///</summary>
		[ImplementPropertyType("link3")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker Link3
		{
			get { return this.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("link3"); }
		}

		///<summary>
		/// Ad
		///</summary>
		[ImplementPropertyType("ad")]
		public IPublishedContent Ad
		{
			get { return Umbraco.Web.PublishedContentModels.AdType.GetAd(this); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return Umbraco.Web.PublishedContentModels.ImageType.GetImage(this); }
		}

		///<summary>
		/// Subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.SubtitleType.GetSubtitle(this); }
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("text")]
		public string Text
		{
			get { return Umbraco.Web.PublishedContentModels.TextType.GetText(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.TitleType.GetTitle(this); }
		}
	}
}
