//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Image Widgets Section</summary>
	[PublishedContentModel("imageWidgetsSection")]
	public partial class ImageWidgetsSection : PublishedContentModel, INavigationPanelBorder, INavigationPanelWidth
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageWidgetsSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageWidgetsSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageWidgetsSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Items Column 1
		///</summary>
		[ImplementPropertyType("itemsColumn1")]
		public IEnumerable<IPublishedContent> ItemsColumn1
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("itemsColumn1"); }
		}

		///<summary>
		/// Items Column 2
		///</summary>
		[ImplementPropertyType("itemsColumn2")]
		public IEnumerable<IPublishedContent> ItemsColumn2
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("itemsColumn2"); }
		}

		///<summary>
		/// Items Column 3
		///</summary>
		[ImplementPropertyType("itemsColumn3")]
		public IEnumerable<IPublishedContent> ItemsColumn3
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("itemsColumn3"); }
		}

		///<summary>
		/// Width Column 1
		///</summary>
		[ImplementPropertyType("widthColumn1")]
		public string WidthColumn1
		{
			get { return this.GetPropertyValue<string>("widthColumn1"); }
		}

		///<summary>
		/// Width Column 2
		///</summary>
		[ImplementPropertyType("widthColumn2")]
		public string WidthColumn2
		{
			get { return this.GetPropertyValue<string>("widthColumn2"); }
		}

		///<summary>
		/// Width Column 3
		///</summary>
		[ImplementPropertyType("widthColumn3")]
		public string WidthColumn3
		{
			get { return this.GetPropertyValue<string>("widthColumn3"); }
		}

		///<summary>
		/// Right Border Line
		///</summary>
		[ImplementPropertyType("rightBorderLine")]
		public bool RightBorderLine
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationPanelBorder.GetRightBorderLine(this); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("width")]
		public string Width
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationPanelWidth.GetWidth(this); }
		}
	}
}
