//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Links Grid Panel</summary>
	[PublishedContentModel("linksGridPanel")]
	public partial class LinksGridPanel : Panel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "linksGridPanel";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LinksGridPanel(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LinksGridPanel, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Links Column 1
		///</summary>
		[ImplementPropertyType("linksColumn1")]
		public Umbraco.Web.Models.RelatedLinks LinksColumn1
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linksColumn1"); }
		}

		///<summary>
		/// Links Column 2
		///</summary>
		[ImplementPropertyType("linksColumn2")]
		public Umbraco.Web.Models.RelatedLinks LinksColumn2
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linksColumn2"); }
		}

		///<summary>
		/// Links Column 3
		///</summary>
		[ImplementPropertyType("linksColumn3")]
		public Umbraco.Web.Models.RelatedLinks LinksColumn3
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linksColumn3"); }
		}
	}
}
