//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1151 with alias "linkType"
	/// <summary>Link Type</summary>
	public partial interface ILinkType : IPublishedContent
	{
		/// <summary>Link</summary>
		Gibe.LinkPicker.Umbraco.Models.LinkPicker Link { get; }
	}

	/// <summary>Link Type</summary>
	[PublishedContentModel("linkType")]
	public partial class LinkType : PublishedContentModel, ILinkType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "linkType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LinkType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LinkType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker Link
		{
			get { return GetLink(this); }
		}

		/// <summary>Static getter for Link</summary>
		public static Gibe.LinkPicker.Umbraco.Models.LinkPicker GetLink(ILinkType that) { return that.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("link"); }
	}
}
