//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1078 with alias "navigationPanelWidth"
	/// <summary>Navigation Panel Width</summary>
	public partial interface INavigationPanelWidth : IPublishedContent
	{
		/// <summary>Width</summary>
		string Width { get; }
	}

	/// <summary>Navigation Panel Width</summary>
	[PublishedContentModel("navigationPanelWidth")]
	public partial class NavigationPanelWidth : PublishedContentModel, INavigationPanelWidth
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationPanelWidth";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationPanelWidth(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationPanelWidth, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("width")]
		public string Width
		{
			get { return GetWidth(this); }
		}

		/// <summary>Static getter for Width</summary>
		public static string GetWidth(INavigationPanelWidth that) { return that.GetPropertyValue<string>("width"); }
	}
}
