//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1095 with alias "navigationPanelBorder"
	/// <summary>Navigation Panel Border</summary>
	public partial interface INavigationPanelBorder : IPublishedContent
	{
		/// <summary>Right Border Line</summary>
		bool RightBorderLine { get; }
	}

	/// <summary>Navigation Panel Border</summary>
	[PublishedContentModel("navigationPanelBorder")]
	public partial class NavigationPanelBorder : PublishedContentModel, INavigationPanelBorder
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationPanelBorder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationPanelBorder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationPanelBorder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Right Border Line
		///</summary>
		[ImplementPropertyType("rightBorderLine")]
		public bool RightBorderLine
		{
			get { return GetRightBorderLine(this); }
		}

		/// <summary>Static getter for Right Border Line</summary>
		public static bool GetRightBorderLine(INavigationPanelBorder that) { return that.GetPropertyValue<bool>("rightBorderLine"); }
	}
}
