//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>News Events Section</summary>
	[PublishedContentModel("newsEventsSection")]
	public partial class NewsEventsSection : ContentSection
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newsEventsSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewsEventsSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewsEventsSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Items
		///</summary>
		[ImplementPropertyType("eventItems")]
		public IEnumerable<IPublishedContent> EventItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("eventItems"); }
		}

		///<summary>
		/// Events Link
		///</summary>
		[ImplementPropertyType("eventsLink")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker EventsLink
		{
			get { return this.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("eventsLink"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("eventsTitle")]
		public string EventsTitle
		{
			get { return this.GetPropertyValue<string>("eventsTitle"); }
		}

		///<summary>
		/// Items
		///</summary>
		[ImplementPropertyType("newsItems")]
		public IEnumerable<IPublishedContent> NewsItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("newsItems"); }
		}

		///<summary>
		/// News Link
		///</summary>
		[ImplementPropertyType("newsLink")]
		public Gibe.LinkPicker.Umbraco.Models.LinkPicker NewsLink
		{
			get { return this.GetPropertyValue<Gibe.LinkPicker.Umbraco.Models.LinkPicker>("newsLink"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("newsTitle")]
		public string NewsTitle
		{
			get { return this.GetPropertyValue<string>("newsTitle"); }
		}
	}
}
